language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t castergen22/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true castergen22/react-test npm test

after_success:
  - docker build -t castergen22/multi-client ./client 
  - docker build -t castergen22/multi-nginx ./nginx
  - docker build -t castergen22/multi-server ./server
  - docker build -t castergen22/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push castergen22/multi-client
  - docker push castergen22/multi-nginx
  - docker push castergen22/multi-server
  - docker push castergen22/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-620967441753
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY